image:
  repository: edenmor1989/restaurant-recommender
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: restaurant-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  STORAGE_ACCOUNT_NAME: restaurantdbstore
  STORAGE_ACCOUNT_KEY: ""
  RESTAURANTS_TABLE_NAME: restaurants
  LOGS_TABLE_NAME: requestlogs
