resource_group_name    = "restaurant-recommendation"
location               = "East Asia"
app_name               = "restaurant-recommendation-app"
app_image              = "edenmor1989/restaurant-recommender:latest"
storage_account_name   = "restaurantdbstore"
restaurants_table_name = "restaurants"
logs_table_name        = "requestlogs"
