name: App Deployment Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:${{ github.run_id }} \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:latest

    # Step 3: Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender --all-tags

  update-app-service:
    name: Update Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # Step 1: Azure CLI Login
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 2: Update App Service Image
    - name: Update Azure App Service Image
      run: |
        az webapp config container set \
          --name "restaurant-recommendation-app" \
          --resource-group "restaurant-recommendation" \
          --docker-custom-image-name "${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:latest" \
          --docker-registry-server-url "https://index.docker.io/v1/" \
          --docker-registry-server-user "${{ secrets.DOCKERHUB_USERNAME }}" \
          --docker-registry-server-password "${{ secrets.DOCKERHUB_TOKEN }}"
