name: App Deployment Pipeline

on:
  push:
    paths:
      - 'app/**'
      - 'data/**'
      - 'dbutil/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'requirements.txt'
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build --platform=linux/amd64 . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:${{ github.run_id }} \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:latest


    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender --all-tags

  update-app-service:
    name: Update Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Update Azure App Service Image
      run: |
        az webapp config container set \
          --name "restaurant-recommendation-app" \
          --resource-group "restaurant-recommendation" \
          --docker-custom-image-name "${{ secrets.DOCKERHUB_USERNAME }}/restaurant-recommender:latest" \
          --docker-registry-server-url "https://index.docker.io/v1/" \
          --docker-registry-server-user "${{ secrets.DOCKERHUB_USERNAME }}" \
          --docker-registry-server-password "${{ secrets.DOCKERHUB_TOKEN }}"
    - name: Update Azure App Service Image
      run: |
          az webapp restart \
            --name "restaurant-recommendation-app" \
            --resource-group "restaurant-recommendation" 