name: Infrastructure Pipeline

on:
#   push:
#     paths:
#       - 'infra/**'
#     branches:
#       - dev
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5


    - name: Initialize Terraform
      run: terraform init
      working-directory: infra/
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve -var="storage_account_key=${{ secrets.AZURE_CLIENT_SECRET }}"
      working-directory: infra/
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
            az storage blob upload \
                --account-name restaurantdbstore \
                --container-name states \
                --file ./infra/terraform.tfstate \
                --name terraform.tfstate